import { render } from '@testing-library/react'
import App from './App'

// Todo: The test was generated by the project starter. Fill it with life or remove it.
test('renders learn react link', () => {
  render(<App />)
})
